### ISSUE TITLE
something wrong in MobilenetV1 

### ISSUE THREAD

**Issue by ImColin-LU** [QDucasse/nn_benchmark#21]
I dont know the function of this code:

`from brevitas.quant_tensor import pack_quant_tensor`
and The file is no longer in the source project.
When i delete  this code to run , I find a bug in forword process.

RuntimeError: The size of tensor a (64) must match the size of tensor b (32) at non-singleton dimension 1.
when the program run to pw

**Comment by QDucasse** [comment]
Hi,
The mobilenet version was a custom implementation at a time where it was not supported in FINN. I believe it has been implemented now and maybe you can take a look at https://github.com/Xilinx/finn-examples where an example is provided!

**Comment by ImColin-LU** [comment]
Hi,
Thank you very much for your reply! After I changed the network model, it is now working. Thank you for your advice.
